
transitclock:
  gtfs:
    url: https://data.opentransport.ro/routing/gtfs/gtfs-stpt.zip
    dirName: /var/transitclock/cache
    intervalMsec: 86400000

  autoBlockAssigner:
    autoAssignerEnabled: true
    ignoreAvlAssignments: false
    allowableEarlySeconds: 600
    allowableLateSeconds: 600

  avl:
    feedTimeoutInMSecs: 30000
    gtfsRealtimeFeedURI: "https://api.opentransport.ro/exporter/v1/realtime/stpt/vehicle-positions"
    maxSpeed: 100
    numThreads: 1
    queueSize: 2400
    minLatitude: 43
    maxLatitude: 48
    maxLongitude: 30
    minLongitude: 20
    feedPollingRateSecs: 15

transitclock.blockLoading.agressive: false

transitclock.cache.core.daysPopulateHistoricalCache: 0

transitclock.core.agencyId: stpt
transitclock.core.allowableEarlyDepartureTimeForLoggingEvent: 180
transitclock.core.allowableEarlyForLayoverSeconds: 1800
transitclock.core.allowableEarlySecondsForInitialMatching: 1200
transitclock.core.allowableEarlyTimeForEarlyDepartureSecs: 180
transitclock.core.allowableLateAtTerminalForLoggingEvent: 240
transitclock.core.allowableLateDepartureTimeForLoggingEvent: 360
transitclock.core.allowableLateSeconds: 2700
transitclock.core.allowableNumberOfBadMatches: 4
transitclock.core.afterStopDistance: 100
transitclock.core.beforeStopDistance: 100
transitclock.core.cache.tripDataHistoryCache: org.transitclock.core.dataCache.ehcache.scheduled.TripDataHistoryCache
transitclock.core.cache.errorCacheClass: org.transitclock.core.dataCache.ehcache.KalmanErrorCache
transitclock.core.cache.stopArrivalDepartureCache: org.transitclock.core.dataCache.ehcache.StopArrivalDepartureCache
transitclock.core.cache.stopPathPredictionCache: org.transitclock.core.dataCache.StopPathPredictionCache
#transitclock.core.cache.stopPathPredictionCache: org.transitclock.core.dataCache.ehcache.dummy.DummyStopPathPredictionCache
transitclock.core.cache.dwellTimeModelCache: org.transitclock.core.dataCache.ehcache.scheduled.DwellTimeModelCache
#transitclock.core.cache.dwellTimeModelCache: org.transitclock.core.dataCache.ehcache.dummy.DummyDwellTimeModelCache
transitclock.core.distanceFromLayoverForEarlyDeparture: 250
transitclock.core.dwelltime.model: org.transitclock.core.predictiongenerator.scheduled.dwell.DwellAverage
transitclock.core.dwelltime.headwayGeneratorClass: org.transitclock.core.headwaygenerator.LastArrivalsHeadwayGenerator
transitclock.core.exclusiveBlockAssignments: true
transitclock.core.fillHistoricalCaches: 0
transitclock.core.layoverDistance: 1000
transitclock.core.longDistanceDeadheadingSpeed: 20
transitclock.core.matchHistoryMaxSize: 40
transitclock.core.maxHeadingOffsetFromSegment: 200
transitclock.core.maxPredictionTimeForDbSecs: 1200
transitclock.core.maxPredictionsTimeSecs: 1800
transitclock.core.minDistanceForDelayed: 60
transitclock.core.minDistanceForNoProgress: 60
transitclock.core.onlyNeedArrivalDepartures: false
#transitclock.core.predictionGeneratorClass: org.transitclock.core.predictiongenerator.scheduled.traveltime.kalman.KalmanPredictionGeneratorImpl
transitclock.core.shortDistanceDeadheadingSpeed: 10
transitclock.core.timeForDeterminingDelayedSecs: 300
transitclock.core.timeForDeterminingNoProgress: 360000
transitclock.core.trackHistoricalCaches: false
transitclock.core.useArrivalPredictionsForNormalStops: false

transitclock.db.batchSize: 4000
transitclock.db.dbName: STPT
transitclock.db.dbPassword: transitclock
transitclock.db.dbUserName: postgres
transitclock.db.dbHost: localhost:5432
transitclock.db.storeDataInDatabase: true
transitclock.db.dbType: postgresql


transitclock.predAccuracy.stopsPerTrip: 1000
transitclock.predAccuracy.maxPredTimeMinutes: 30

transitclock.prediction.data.kalman.mindays: 3
transitclock.prediction.data.kalman.maxdays: 5
transitclock.prediction.data.kalman.maxdaystosearch: 21
transitclock.prediction.data.kalman.percentagePredictionMethodDifferencene: 50
transitclock.prediction.data.kalman.tresholdForDifferenceEventLog: 60000
transitclock.prediction.rls.lambda: 0.9

transitclock.timeout.pollingRateSecs: 60

transitclock.modules.optionalModulesList: org.transitclock.core.avl.GtfsRealtimeModule;org.transitclock.core.predAccuracy.PredictionAccuracyModule;org.transitclock.gtfs.GtfsUpdatedModule
transitclock.hibernate.configFile: /home/opentransport/transitime/app/src/main/jib/app/config/hibernate.cfg.xml
transitclock.logging.dir: /var/transitclock/logs
transitclock.web.mapTileUrl: http://tile.openstreetmap.org/{z}/{x}/{y}.png


spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: transitclock
    hikari:
      auto-commit: true
    url: jdbc:postgresql://localhost:5432/STPT
